import Head from 'next/head';
import { useEffect } from 'react';
import styles from '../styles/Home.module.css';
import SignUpForm from '../components/SignUpForm';

export default function Home() {
  let faceio;

  useEffect(() => {
    faceio = new faceIO('fioa414d');
  }, []);

  const handleSignIn = async () => {
    try {
      let response = await faceio.enroll({
        locale: 'auto',
        payload: {
          email: 'example@gmail.com',
          pin: '12345',
        },
      });

      console.log(` Unique Facial ID: ${response.facialId}
    Enrollment Date: ${response.timestamp}
    Gender: ${response.details.gender}
    Age Approximation: ${response.details.age}`);
    } catch (error) {
      console.log(error);
    }
  };

  const handleLogIn = async () => {
    try {
      let response = await faceio.authenticate({
        locale: 'auto',
      });

      console.log(` Unique Facial ID: ${response.facialId}
        PayLoad: ${response.payload}
        `);
    } catch (error) {
      console.log(error);
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>klpkl</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <section>
          <SignUpForm />
          {/* <h1>Face Authentication by FaceIO</h1>
          <button onClick={handleSignIn}>Sign-in</button>
          <button onClick={handleLogIn}>Log-in</button> */}
        </section>
      </main>
    </div>
  );
}
